"""File Generated by Sideko (sideko.dev)"""

import io
import typing
import typing_extensions
from pydantic import (
    BaseModel as _PydanticBaseModel,
    Field as _PydanticField,
    ConfigDict as _PydanticConfigDict,
)

ModelFiles = typing.List[
    typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]
]


class InAppPurchaseV2Attributes(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    content_hosting: typing.Optional[bool] = _PydanticField(
        alias="contentHosting", default=None
    )
    family_sharable: typing.Optional[bool] = _PydanticField(
        alias="familySharable", default=None
    )
    in_app_purchase_type: typing.Optional[
        typing_extensions.Literal[
            "CONSUMABLE", "NON_CONSUMABLE", "NON_RENEWING_SUBSCRIPTION"
        ]
    ] = _PydanticField(alias="inAppPurchaseType", default=None)
    name: typing.Optional[str] = _PydanticField(alias="name", default=None)
    product_id: typing.Optional[str] = _PydanticField(alias="productId", default=None)
    review_note: typing.Optional[str] = _PydanticField(alias="reviewNote", default=None)
    state: typing.Optional[
        typing_extensions.Literal[
            "MISSING_METADATA",
            "WAITING_FOR_UPLOAD",
            "PROCESSING_CONTENT",
            "READY_TO_SUBMIT",
            "WAITING_FOR_REVIEW",
            "IN_REVIEW",
            "DEVELOPER_ACTION_NEEDED",
            "PENDING_BINARY_APPROVAL",
            "APPROVED",
            "DEVELOPER_REMOVED_FROM_SALE",
            "REMOVED_FROM_SALE",
            "REJECTED",
        ]
    ] = _PydanticField(alias="state", default=None)


class ResourceLinks(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    self: typing.Optional[str] = _PydanticField(alias="self", default=None)


class InAppPurchaseV2RelationshipsAppStoreReviewScreenshotData(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: str = _PydanticField(alias="id")
    type: typing_extensions.Literal["inAppPurchaseAppStoreReviewScreenshots"] = (
        _PydanticField(alias="type")
    )


class InAppPurchaseV2RelationshipsAppStoreReviewScreenshotLinks(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    related: typing.Optional[str] = _PydanticField(alias="related", default=None)
    self: typing.Optional[str] = _PydanticField(alias="self", default=None)


class InAppPurchaseV2RelationshipsContentData(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: str = _PydanticField(alias="id")
    type: typing_extensions.Literal["inAppPurchaseContents"] = _PydanticField(
        alias="type"
    )


class InAppPurchaseV2RelationshipsContentLinks(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    related: typing.Optional[str] = _PydanticField(alias="related", default=None)
    self: typing.Optional[str] = _PydanticField(alias="self", default=None)


class InAppPurchaseV2RelationshipsIapPriceScheduleData(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: str = _PydanticField(alias="id")
    type: typing_extensions.Literal["inAppPurchasePriceSchedules"] = _PydanticField(
        alias="type"
    )


class InAppPurchaseV2RelationshipsIapPriceScheduleLinks(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    related: typing.Optional[str] = _PydanticField(alias="related", default=None)
    self: typing.Optional[str] = _PydanticField(alias="self", default=None)


class InAppPurchaseV2RelationshipsInAppPurchaseAvailabilityData(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: str = _PydanticField(alias="id")
    type: typing_extensions.Literal["inAppPurchaseAvailabilities"] = _PydanticField(
        alias="type"
    )


class InAppPurchaseV2RelationshipsInAppPurchaseAvailabilityLinks(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    related: typing.Optional[str] = _PydanticField(alias="related", default=None)
    self: typing.Optional[str] = _PydanticField(alias="self", default=None)


class InAppPurchaseV2RelationshipsInAppPurchaseLocalizationsDataItem(
    _PydanticBaseModel
):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: str = _PydanticField(alias="id")
    type: typing_extensions.Literal["inAppPurchaseLocalizations"] = _PydanticField(
        alias="type"
    )


class InAppPurchaseV2RelationshipsInAppPurchaseLocalizationsLinks(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    related: typing.Optional[str] = _PydanticField(alias="related", default=None)
    self: typing.Optional[str] = _PydanticField(alias="self", default=None)


class PagingInformationPaging(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    limit: int = _PydanticField(alias="limit")
    total: typing.Optional[int] = _PydanticField(alias="total", default=None)


class InAppPurchaseV2RelationshipsPricePointsDataItem(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: str = _PydanticField(alias="id")
    type: typing_extensions.Literal["inAppPurchasePricePoints"] = _PydanticField(
        alias="type"
    )


class InAppPurchaseV2RelationshipsPricePointsLinks(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    related: typing.Optional[str] = _PydanticField(alias="related", default=None)
    self: typing.Optional[str] = _PydanticField(alias="self", default=None)


class InAppPurchaseV2RelationshipsPromotedPurchaseData(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: str = _PydanticField(alias="id")
    type: typing_extensions.Literal["promotedPurchases"] = _PydanticField(alias="type")


class InAppPurchaseV2RelationshipsPromotedPurchaseLinks(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    related: typing.Optional[str] = _PydanticField(alias="related", default=None)
    self: typing.Optional[str] = _PydanticField(alias="self", default=None)


class InAppPurchaseLocalizationAttributes(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    description: typing.Optional[str] = _PydanticField(
        alias="description", default=None
    )
    locale_field: typing.Optional[str] = _PydanticField(alias="locale", default=None)
    name: typing.Optional[str] = _PydanticField(alias="name", default=None)
    state: typing.Optional[
        typing_extensions.Literal[
            "PREPARE_FOR_SUBMISSION", "WAITING_FOR_REVIEW", "APPROVED", "REJECTED"
        ]
    ] = _PydanticField(alias="state", default=None)


class InAppPurchaseLocalizationRelationshipsInAppPurchaseV2Data(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: str = _PydanticField(alias="id")
    type: typing_extensions.Literal["inAppPurchases"] = _PydanticField(alias="type")


class InAppPurchaseLocalizationRelationshipsInAppPurchaseV2Links(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    related: typing.Optional[str] = _PydanticField(alias="related", default=None)
    self: typing.Optional[str] = _PydanticField(alias="self", default=None)


class InAppPurchasePricePointAttributes(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    customer_price: typing.Optional[str] = _PydanticField(
        alias="customerPrice", default=None
    )
    proceeds: typing.Optional[str] = _PydanticField(alias="proceeds", default=None)


class InAppPurchasePricePointRelationshipsTerritoryData(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: str = _PydanticField(alias="id")
    type: typing_extensions.Literal["territories"] = _PydanticField(alias="type")


class InAppPurchasePricePointRelationshipsTerritoryLinks(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    related: typing.Optional[str] = _PydanticField(alias="related", default=None)
    self: typing.Optional[str] = _PydanticField(alias="self", default=None)


class InAppPurchaseContentAttributes(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    file_name: typing.Optional[str] = _PydanticField(alias="fileName", default=None)
    file_size: typing.Optional[int] = _PydanticField(alias="fileSize", default=None)
    last_modified_date: typing.Optional[str] = _PydanticField(
        alias="lastModifiedDate", default=None
    )
    url: typing.Optional[str] = _PydanticField(alias="url", default=None)


class InAppPurchaseContentRelationshipsInAppPurchaseV2Data(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: str = _PydanticField(alias="id")
    type: typing_extensions.Literal["inAppPurchases"] = _PydanticField(alias="type")


class InAppPurchaseContentRelationshipsInAppPurchaseV2Links(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    related: typing.Optional[str] = _PydanticField(alias="related", default=None)
    self: typing.Optional[str] = _PydanticField(alias="self", default=None)


class AppMediaStateError(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    code_field: typing.Optional[str] = _PydanticField(alias="code", default=None)
    description: typing.Optional[str] = _PydanticField(
        alias="description", default=None
    )


class ImageAsset(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    height: typing.Optional[int] = _PydanticField(alias="height", default=None)
    template_url: typing.Optional[str] = _PydanticField(
        alias="templateUrl", default=None
    )
    width: typing.Optional[int] = _PydanticField(alias="width", default=None)


class HttpHeader(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    name: typing.Optional[str] = _PydanticField(alias="name", default=None)
    value: typing.Optional[str] = _PydanticField(alias="value", default=None)


class InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2Data(
    _PydanticBaseModel
):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: str = _PydanticField(alias="id")
    type: typing_extensions.Literal["inAppPurchases"] = _PydanticField(alias="type")


class InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2Links(
    _PydanticBaseModel
):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    related: typing.Optional[str] = _PydanticField(alias="related", default=None)
    self: typing.Optional[str] = _PydanticField(alias="self", default=None)


class PromotedPurchaseAttributes(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    enabled: typing.Optional[bool] = _PydanticField(alias="enabled", default=None)
    state: typing.Optional[
        typing_extensions.Literal[
            "APPROVED", "IN_REVIEW", "PREPARE_FOR_SUBMISSION", "REJECTED"
        ]
    ] = _PydanticField(alias="state", default=None)
    visible_for_all_users: typing.Optional[bool] = _PydanticField(
        alias="visibleForAllUsers", default=None
    )


class PromotedPurchaseRelationshipsInAppPurchaseV2Data(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: str = _PydanticField(alias="id")
    type: typing_extensions.Literal["inAppPurchases"] = _PydanticField(alias="type")


class PromotedPurchaseRelationshipsInAppPurchaseV2Links(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    related: typing.Optional[str] = _PydanticField(alias="related", default=None)
    self: typing.Optional[str] = _PydanticField(alias="self", default=None)


class PromotedPurchaseRelationshipsPromotionImagesDataItem(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: str = _PydanticField(alias="id")
    type: typing_extensions.Literal["promotedPurchaseImages"] = _PydanticField(
        alias="type"
    )


class PromotedPurchaseRelationshipsPromotionImagesLinks(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    related: typing.Optional[str] = _PydanticField(alias="related", default=None)
    self: typing.Optional[str] = _PydanticField(alias="self", default=None)


class PromotedPurchaseRelationshipsSubscriptionData(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: str = _PydanticField(alias="id")
    type: typing_extensions.Literal["subscriptions"] = _PydanticField(alias="type")


class PromotedPurchaseRelationshipsSubscriptionLinks(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    related: typing.Optional[str] = _PydanticField(alias="related", default=None)
    self: typing.Optional[str] = _PydanticField(alias="self", default=None)


class InAppPurchasePriceScheduleRelationshipsAutomaticPricesDataItem(
    _PydanticBaseModel
):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: str = _PydanticField(alias="id")
    type: typing_extensions.Literal["inAppPurchasePrices"] = _PydanticField(
        alias="type"
    )


class InAppPurchasePriceScheduleRelationshipsAutomaticPricesLinks(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    related: typing.Optional[str] = _PydanticField(alias="related", default=None)
    self: typing.Optional[str] = _PydanticField(alias="self", default=None)


class InAppPurchasePriceScheduleRelationshipsBaseTerritoryData(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: str = _PydanticField(alias="id")
    type: typing_extensions.Literal["territories"] = _PydanticField(alias="type")


class InAppPurchasePriceScheduleRelationshipsBaseTerritoryLinks(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    related: typing.Optional[str] = _PydanticField(alias="related", default=None)
    self: typing.Optional[str] = _PydanticField(alias="self", default=None)


class InAppPurchasePriceScheduleRelationshipsInAppPurchaseData(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: str = _PydanticField(alias="id")
    type: typing_extensions.Literal["inAppPurchases"] = _PydanticField(alias="type")


class InAppPurchasePriceScheduleRelationshipsInAppPurchaseLinks(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    related: typing.Optional[str] = _PydanticField(alias="related", default=None)
    self: typing.Optional[str] = _PydanticField(alias="self", default=None)


class InAppPurchasePriceScheduleRelationshipsManualPricesDataItem(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: str = _PydanticField(alias="id")
    type: typing_extensions.Literal["inAppPurchasePrices"] = _PydanticField(
        alias="type"
    )


class InAppPurchasePriceScheduleRelationshipsManualPricesLinks(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    related: typing.Optional[str] = _PydanticField(alias="related", default=None)
    self: typing.Optional[str] = _PydanticField(alias="self", default=None)


class InAppPurchaseAvailabilityAttributes(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    available_in_new_territories: typing.Optional[bool] = _PydanticField(
        alias="availableInNewTerritories", default=None
    )


class InAppPurchaseAvailabilityRelationshipsAvailableTerritoriesDataItem(
    _PydanticBaseModel
):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: str = _PydanticField(alias="id")
    type: typing_extensions.Literal["territories"] = _PydanticField(alias="type")


class InAppPurchaseAvailabilityRelationshipsAvailableTerritoriesLinks(
    _PydanticBaseModel
):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    related: typing.Optional[str] = _PydanticField(alias="related", default=None)
    self: typing.Optional[str] = _PydanticField(alias="self", default=None)


class DocumentLinks(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    self: str = _PydanticField(alias="self")


class InAppPurchaseV2RelationshipsAppStoreReviewScreenshot(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    data: typing.Optional[InAppPurchaseV2RelationshipsAppStoreReviewScreenshotData] = (
        _PydanticField(alias="data", default=None)
    )
    links: typing.Optional[
        InAppPurchaseV2RelationshipsAppStoreReviewScreenshotLinks
    ] = _PydanticField(alias="links", default=None)


class InAppPurchaseV2RelationshipsContent(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    data: typing.Optional[InAppPurchaseV2RelationshipsContentData] = _PydanticField(
        alias="data", default=None
    )
    links: typing.Optional[InAppPurchaseV2RelationshipsContentLinks] = _PydanticField(
        alias="links", default=None
    )


class InAppPurchaseV2RelationshipsIapPriceSchedule(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    data: typing.Optional[InAppPurchaseV2RelationshipsIapPriceScheduleData] = (
        _PydanticField(alias="data", default=None)
    )
    links: typing.Optional[InAppPurchaseV2RelationshipsIapPriceScheduleLinks] = (
        _PydanticField(alias="links", default=None)
    )


class InAppPurchaseV2RelationshipsInAppPurchaseAvailability(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    data: typing.Optional[InAppPurchaseV2RelationshipsInAppPurchaseAvailabilityData] = (
        _PydanticField(alias="data", default=None)
    )
    links: typing.Optional[
        InAppPurchaseV2RelationshipsInAppPurchaseAvailabilityLinks
    ] = _PydanticField(alias="links", default=None)


class PagingInformation(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    paging: PagingInformationPaging = _PydanticField(alias="paging")


class InAppPurchaseV2RelationshipsPricePoints(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    data: typing.Optional[
        typing.List[InAppPurchaseV2RelationshipsPricePointsDataItem]
    ] = _PydanticField(alias="data", default=None)
    links: typing.Optional[InAppPurchaseV2RelationshipsPricePointsLinks] = (
        _PydanticField(alias="links", default=None)
    )
    meta: typing.Optional[PagingInformation] = _PydanticField(
        alias="meta", default=None
    )


class InAppPurchaseV2RelationshipsPromotedPurchase(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    data: typing.Optional[InAppPurchaseV2RelationshipsPromotedPurchaseData] = (
        _PydanticField(alias="data", default=None)
    )
    links: typing.Optional[InAppPurchaseV2RelationshipsPromotedPurchaseLinks] = (
        _PydanticField(alias="links", default=None)
    )


class InAppPurchaseLocalizationRelationshipsInAppPurchaseV2(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    data: typing.Optional[InAppPurchaseLocalizationRelationshipsInAppPurchaseV2Data] = (
        _PydanticField(alias="data", default=None)
    )
    links: typing.Optional[
        InAppPurchaseLocalizationRelationshipsInAppPurchaseV2Links
    ] = _PydanticField(alias="links", default=None)


class InAppPurchasePricePointRelationshipsTerritory(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    data: typing.Optional[InAppPurchasePricePointRelationshipsTerritoryData] = (
        _PydanticField(alias="data", default=None)
    )
    links: typing.Optional[InAppPurchasePricePointRelationshipsTerritoryLinks] = (
        _PydanticField(alias="links", default=None)
    )


class InAppPurchaseContentRelationshipsInAppPurchaseV2(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    data: typing.Optional[InAppPurchaseContentRelationshipsInAppPurchaseV2Data] = (
        _PydanticField(alias="data", default=None)
    )
    links: typing.Optional[InAppPurchaseContentRelationshipsInAppPurchaseV2Links] = (
        _PydanticField(alias="links", default=None)
    )


class AppMediaAssetState(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    errors: typing.Optional[typing.List[AppMediaStateError]] = _PydanticField(
        alias="errors", default=None
    )
    state: typing.Optional[
        typing_extensions.Literal[
            "AWAITING_UPLOAD", "UPLOAD_COMPLETE", "COMPLETE", "FAILED"
        ]
    ] = _PydanticField(alias="state", default=None)
    warnings_field: typing.Optional[typing.List[AppMediaStateError]] = _PydanticField(
        alias="warnings", default=None
    )


class UploadOperation(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    length: typing.Optional[int] = _PydanticField(alias="length", default=None)
    method: typing.Optional[str] = _PydanticField(alias="method", default=None)
    offset: typing.Optional[int] = _PydanticField(alias="offset", default=None)
    request_headers: typing.Optional[typing.List[HttpHeader]] = _PydanticField(
        alias="requestHeaders", default=None
    )
    url: typing.Optional[str] = _PydanticField(alias="url", default=None)


class InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2(
    _PydanticBaseModel
):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    data: typing.Optional[
        InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2Data
    ] = _PydanticField(alias="data", default=None)
    links: typing.Optional[
        InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2Links
    ] = _PydanticField(alias="links", default=None)


class PromotedPurchaseRelationshipsInAppPurchaseV2(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    data: typing.Optional[PromotedPurchaseRelationshipsInAppPurchaseV2Data] = (
        _PydanticField(alias="data", default=None)
    )
    links: typing.Optional[PromotedPurchaseRelationshipsInAppPurchaseV2Links] = (
        _PydanticField(alias="links", default=None)
    )


class PromotedPurchaseRelationshipsPromotionImages(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    data: typing.Optional[
        typing.List[PromotedPurchaseRelationshipsPromotionImagesDataItem]
    ] = _PydanticField(alias="data", default=None)
    links: typing.Optional[PromotedPurchaseRelationshipsPromotionImagesLinks] = (
        _PydanticField(alias="links", default=None)
    )
    meta: typing.Optional[PagingInformation] = _PydanticField(
        alias="meta", default=None
    )


class PromotedPurchaseRelationshipsSubscription(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    data: typing.Optional[PromotedPurchaseRelationshipsSubscriptionData] = (
        _PydanticField(alias="data", default=None)
    )
    links: typing.Optional[PromotedPurchaseRelationshipsSubscriptionLinks] = (
        _PydanticField(alias="links", default=None)
    )


class InAppPurchasePriceScheduleRelationshipsAutomaticPrices(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    data: typing.Optional[
        typing.List[InAppPurchasePriceScheduleRelationshipsAutomaticPricesDataItem]
    ] = _PydanticField(alias="data", default=None)
    links: typing.Optional[
        InAppPurchasePriceScheduleRelationshipsAutomaticPricesLinks
    ] = _PydanticField(alias="links", default=None)
    meta: typing.Optional[PagingInformation] = _PydanticField(
        alias="meta", default=None
    )


class InAppPurchasePriceScheduleRelationshipsBaseTerritory(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    data: typing.Optional[InAppPurchasePriceScheduleRelationshipsBaseTerritoryData] = (
        _PydanticField(alias="data", default=None)
    )
    links: typing.Optional[
        InAppPurchasePriceScheduleRelationshipsBaseTerritoryLinks
    ] = _PydanticField(alias="links", default=None)


class InAppPurchasePriceScheduleRelationshipsInAppPurchase(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    data: typing.Optional[InAppPurchasePriceScheduleRelationshipsInAppPurchaseData] = (
        _PydanticField(alias="data", default=None)
    )
    links: typing.Optional[
        InAppPurchasePriceScheduleRelationshipsInAppPurchaseLinks
    ] = _PydanticField(alias="links", default=None)


class InAppPurchasePriceScheduleRelationshipsManualPrices(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    data: typing.Optional[
        typing.List[InAppPurchasePriceScheduleRelationshipsManualPricesDataItem]
    ] = _PydanticField(alias="data", default=None)
    links: typing.Optional[InAppPurchasePriceScheduleRelationshipsManualPricesLinks] = (
        _PydanticField(alias="links", default=None)
    )
    meta: typing.Optional[PagingInformation] = _PydanticField(
        alias="meta", default=None
    )


class InAppPurchaseAvailabilityRelationshipsAvailableTerritories(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    data: typing.Optional[
        typing.List[InAppPurchaseAvailabilityRelationshipsAvailableTerritoriesDataItem]
    ] = _PydanticField(alias="data", default=None)
    links: typing.Optional[
        InAppPurchaseAvailabilityRelationshipsAvailableTerritoriesLinks
    ] = _PydanticField(alias="links", default=None)
    meta: typing.Optional[PagingInformation] = _PydanticField(
        alias="meta", default=None
    )


class InAppPurchaseV2RelationshipsInAppPurchaseLocalizations(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    data: typing.Optional[
        typing.List[InAppPurchaseV2RelationshipsInAppPurchaseLocalizationsDataItem]
    ] = _PydanticField(alias="data", default=None)
    links: typing.Optional[
        InAppPurchaseV2RelationshipsInAppPurchaseLocalizationsLinks
    ] = _PydanticField(alias="links", default=None)
    meta: typing.Optional[PagingInformation] = _PydanticField(
        alias="meta", default=None
    )


class InAppPurchaseLocalizationRelationships(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    in_app_purchase_v2: typing.Optional[
        InAppPurchaseLocalizationRelationshipsInAppPurchaseV2
    ] = _PydanticField(alias="inAppPurchaseV2", default=None)


class InAppPurchasePricePointRelationships(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    territory: typing.Optional[InAppPurchasePricePointRelationshipsTerritory] = (
        _PydanticField(alias="territory", default=None)
    )


class InAppPurchaseContentRelationships(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    in_app_purchase_v2: typing.Optional[
        InAppPurchaseContentRelationshipsInAppPurchaseV2
    ] = _PydanticField(alias="inAppPurchaseV2", default=None)


class InAppPurchaseAppStoreReviewScreenshotAttributes(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    asset_delivery_state: typing.Optional[AppMediaAssetState] = _PydanticField(
        alias="assetDeliveryState", default=None
    )
    asset_token: typing.Optional[str] = _PydanticField(alias="assetToken", default=None)
    asset_type: typing.Optional[str] = _PydanticField(alias="assetType", default=None)
    file_name: typing.Optional[str] = _PydanticField(alias="fileName", default=None)
    file_size: typing.Optional[int] = _PydanticField(alias="fileSize", default=None)
    image_asset: typing.Optional[ImageAsset] = _PydanticField(
        alias="imageAsset", default=None
    )
    source_file_checksum: typing.Optional[str] = _PydanticField(
        alias="sourceFileChecksum", default=None
    )
    upload_operations: typing.Optional[typing.List[UploadOperation]] = _PydanticField(
        alias="uploadOperations", default=None
    )


class InAppPurchaseAppStoreReviewScreenshotRelationships(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    in_app_purchase_v2: typing.Optional[
        InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2
    ] = _PydanticField(alias="inAppPurchaseV2", default=None)


class PromotedPurchaseRelationships(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    in_app_purchase_v2: typing.Optional[
        PromotedPurchaseRelationshipsInAppPurchaseV2
    ] = _PydanticField(alias="inAppPurchaseV2", default=None)
    promotion_images: typing.Optional[PromotedPurchaseRelationshipsPromotionImages] = (
        _PydanticField(alias="promotionImages", default=None)
    )
    subscription: typing.Optional[PromotedPurchaseRelationshipsSubscription] = (
        _PydanticField(alias="subscription", default=None)
    )


class InAppPurchasePriceScheduleRelationships(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    automatic_prices: typing.Optional[
        InAppPurchasePriceScheduleRelationshipsAutomaticPrices
    ] = _PydanticField(alias="automaticPrices", default=None)
    base_territory: typing.Optional[
        InAppPurchasePriceScheduleRelationshipsBaseTerritory
    ] = _PydanticField(alias="baseTerritory", default=None)
    in_app_purchase: typing.Optional[
        InAppPurchasePriceScheduleRelationshipsInAppPurchase
    ] = _PydanticField(alias="inAppPurchase", default=None)
    manual_prices: typing.Optional[
        InAppPurchasePriceScheduleRelationshipsManualPrices
    ] = _PydanticField(alias="manualPrices", default=None)


class InAppPurchaseAvailabilityRelationships(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    available_territories: typing.Optional[
        InAppPurchaseAvailabilityRelationshipsAvailableTerritories
    ] = _PydanticField(alias="availableTerritories", default=None)


class InAppPurchaseV2Relationships(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    app_store_review_screenshot: typing.Optional[
        InAppPurchaseV2RelationshipsAppStoreReviewScreenshot
    ] = _PydanticField(alias="appStoreReviewScreenshot", default=None)
    content: typing.Optional[InAppPurchaseV2RelationshipsContent] = _PydanticField(
        alias="content", default=None
    )
    iap_price_schedule: typing.Optional[
        InAppPurchaseV2RelationshipsIapPriceSchedule
    ] = _PydanticField(alias="iapPriceSchedule", default=None)
    in_app_purchase_availability: typing.Optional[
        InAppPurchaseV2RelationshipsInAppPurchaseAvailability
    ] = _PydanticField(alias="inAppPurchaseAvailability", default=None)
    in_app_purchase_localizations: typing.Optional[
        InAppPurchaseV2RelationshipsInAppPurchaseLocalizations
    ] = _PydanticField(alias="inAppPurchaseLocalizations", default=None)
    price_points: typing.Optional[InAppPurchaseV2RelationshipsPricePoints] = (
        _PydanticField(alias="pricePoints", default=None)
    )
    promoted_purchase: typing.Optional[InAppPurchaseV2RelationshipsPromotedPurchase] = (
        _PydanticField(alias="promotedPurchase", default=None)
    )


class InAppPurchaseLocalization(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    attributes: typing.Optional[InAppPurchaseLocalizationAttributes] = _PydanticField(
        alias="attributes", default=None
    )
    id: str = _PydanticField(alias="id")
    links: typing.Optional[ResourceLinks] = _PydanticField(alias="links", default=None)
    relationships: typing.Optional[InAppPurchaseLocalizationRelationships] = (
        _PydanticField(alias="relationships", default=None)
    )
    type: typing_extensions.Literal["inAppPurchaseLocalizations"] = _PydanticField(
        alias="type"
    )


class InAppPurchasePricePoint(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    attributes: typing.Optional[InAppPurchasePricePointAttributes] = _PydanticField(
        alias="attributes", default=None
    )
    id: str = _PydanticField(alias="id")
    links: typing.Optional[ResourceLinks] = _PydanticField(alias="links", default=None)
    relationships: typing.Optional[InAppPurchasePricePointRelationships] = (
        _PydanticField(alias="relationships", default=None)
    )
    type: typing_extensions.Literal["inAppPurchasePricePoints"] = _PydanticField(
        alias="type"
    )


class InAppPurchaseContent(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    attributes: typing.Optional[InAppPurchaseContentAttributes] = _PydanticField(
        alias="attributes", default=None
    )
    id: str = _PydanticField(alias="id")
    links: typing.Optional[ResourceLinks] = _PydanticField(alias="links", default=None)
    relationships: typing.Optional[InAppPurchaseContentRelationships] = _PydanticField(
        alias="relationships", default=None
    )
    type: typing_extensions.Literal["inAppPurchaseContents"] = _PydanticField(
        alias="type"
    )


class InAppPurchaseAppStoreReviewScreenshot(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    attributes: typing.Optional[InAppPurchaseAppStoreReviewScreenshotAttributes] = (
        _PydanticField(alias="attributes", default=None)
    )
    id: str = _PydanticField(alias="id")
    links: typing.Optional[ResourceLinks] = _PydanticField(alias="links", default=None)
    relationships: typing.Optional[
        InAppPurchaseAppStoreReviewScreenshotRelationships
    ] = _PydanticField(alias="relationships", default=None)
    type: typing_extensions.Literal["inAppPurchaseAppStoreReviewScreenshots"] = (
        _PydanticField(alias="type")
    )


class PromotedPurchase(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    attributes: typing.Optional[PromotedPurchaseAttributes] = _PydanticField(
        alias="attributes", default=None
    )
    id: str = _PydanticField(alias="id")
    links: typing.Optional[ResourceLinks] = _PydanticField(alias="links", default=None)
    relationships: typing.Optional[PromotedPurchaseRelationships] = _PydanticField(
        alias="relationships", default=None
    )
    type: typing_extensions.Literal["promotedPurchases"] = _PydanticField(alias="type")


class InAppPurchasePriceSchedule(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: str = _PydanticField(alias="id")
    links: typing.Optional[ResourceLinks] = _PydanticField(alias="links", default=None)
    relationships: typing.Optional[InAppPurchasePriceScheduleRelationships] = (
        _PydanticField(alias="relationships", default=None)
    )
    type: typing_extensions.Literal["inAppPurchasePriceSchedules"] = _PydanticField(
        alias="type"
    )


class InAppPurchaseAvailability(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    attributes: typing.Optional[InAppPurchaseAvailabilityAttributes] = _PydanticField(
        alias="attributes", default=None
    )
    id: str = _PydanticField(alias="id")
    links: typing.Optional[ResourceLinks] = _PydanticField(alias="links", default=None)
    relationships: typing.Optional[InAppPurchaseAvailabilityRelationships] = (
        _PydanticField(alias="relationships", default=None)
    )
    type: typing_extensions.Literal["inAppPurchaseAvailabilities"] = _PydanticField(
        alias="type"
    )


class InAppPurchaseV2(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    attributes: typing.Optional[InAppPurchaseV2Attributes] = _PydanticField(
        alias="attributes", default=None
    )
    id: str = _PydanticField(alias="id")
    links: typing.Optional[ResourceLinks] = _PydanticField(alias="links", default=None)
    relationships: typing.Optional[InAppPurchaseV2Relationships] = _PydanticField(
        alias="relationships", default=None
    )
    type: typing_extensions.Literal["inAppPurchases"] = _PydanticField(alias="type")


class InAppPurchaseV2Response(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    data: InAppPurchaseV2 = _PydanticField(alias="data")
    included: typing.Optional[
        typing.List[
            typing.Union[
                InAppPurchaseLocalization,
                InAppPurchasePricePoint,
                InAppPurchaseContent,
                InAppPurchaseAppStoreReviewScreenshot,
                PromotedPurchase,
                InAppPurchasePriceSchedule,
                InAppPurchaseAvailability,
            ]
        ]
    ] = _PydanticField(alias="included", default=None)
    links: DocumentLinks = _PydanticField(alias="links")
