"""File Generated by Sideko (sideko.dev)"""

from .resource_client import (
    InAppPurchaseLocalizationsClient,
    AsyncInAppPurchaseLocalizationsClient,
)


__all__ = ["InAppPurchaseLocalizationsClient", "AsyncInAppPurchaseLocalizationsClient"]
