"""File Generated by Sideko (sideko.dev)"""

from apple_python.core import (
    AsyncBaseClient,
    RequestOptions,
    QueryParams,
    SyncBaseClient,
    default_request_options,
    encode_param,
)
import typing
import typing_extensions
from apple_python.types.v1.app_custom_product_pages.app_custom_product_page_versions import (
    models,
)


class AppCustomProductPageVersionsClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)

    # register sync api methods (keep comment for code generation)
    def list(
        self,
        *,
        id: str,
        fields_app_custom_product_page_localizations: typing.Optional[
            typing.List[
                typing_extensions.Literal[
                    "appCustomProductPageVersion",
                    "appPreviewSets",
                    "appScreenshotSets",
                    "locale",
                    "promotionalText",
                ]
            ]
        ] = None,
        fields_app_custom_product_page_versions: typing.Optional[
            typing.List[
                typing_extensions.Literal[
                    "appCustomProductPage",
                    "appCustomProductPageLocalizations",
                    "deepLink",
                    "state",
                    "version",
                ]
            ]
        ] = None,
        fields_app_custom_product_pages: typing.Optional[
            typing.List[
                typing_extensions.Literal[
                    "app",
                    "appCustomProductPageVersions",
                    "appStoreVersionTemplate",
                    "customProductPageTemplate",
                    "name",
                    "url",
                    "visible",
                ]
            ]
        ] = None,
        filter_state: typing.Optional[
            typing.List[
                typing_extensions.Literal[
                    "PREPARE_FOR_SUBMISSION",
                    "READY_FOR_REVIEW",
                    "WAITING_FOR_REVIEW",
                    "IN_REVIEW",
                    "ACCEPTED",
                    "APPROVED",
                    "REPLACED_WITH_NEW_VERSION",
                    "REJECTED",
                ]
            ]
        ] = None,
        include: typing.Optional[
            typing.List[
                typing_extensions.Literal[
                    "appCustomProductPage", "appCustomProductPageLocalizations"
                ]
            ]
        ] = None,
        limit: typing.Optional[int] = None,
        limit_app_custom_product_page_localizations: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.AppCustomProductPageVersionsResponse:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if fields_app_custom_product_page_localizations is not None:
            _query["fields[appCustomProductPageLocalizations]"] = encode_param(
                fields_app_custom_product_page_localizations, False
            )
        if fields_app_custom_product_page_versions is not None:
            _query["fields[appCustomProductPageVersions]"] = encode_param(
                fields_app_custom_product_page_versions, False
            )
        if fields_app_custom_product_pages is not None:
            _query["fields[appCustomProductPages]"] = encode_param(
                fields_app_custom_product_pages, False
            )
        if filter_state is not None:
            _query["filter[state]"] = encode_param(filter_state, False)
        if include is not None:
            _query["include"] = encode_param(include, False)
        if limit is not None:
            _query["limit"] = encode_param(limit, False)
        if limit_app_custom_product_page_localizations is not None:
            _query["limit[appCustomProductPageLocalizations]"] = encode_param(
                limit_app_custom_product_page_localizations, False
            )
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="GET",
            path=f"/v1/appCustomProductPages/{id}/appCustomProductPageVersions",
            auth_names=["itc-bearer-token"],
            query_params=_query,
            cast_to=models.AppCustomProductPageVersionsResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncAppCustomProductPageVersionsClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)

    # register async api methods (keep comment for code generation)
    async def list(
        self,
        *,
        id: str,
        fields_app_custom_product_page_localizations: typing.Optional[
            typing.List[
                typing_extensions.Literal[
                    "appCustomProductPageVersion",
                    "appPreviewSets",
                    "appScreenshotSets",
                    "locale",
                    "promotionalText",
                ]
            ]
        ] = None,
        fields_app_custom_product_page_versions: typing.Optional[
            typing.List[
                typing_extensions.Literal[
                    "appCustomProductPage",
                    "appCustomProductPageLocalizations",
                    "deepLink",
                    "state",
                    "version",
                ]
            ]
        ] = None,
        fields_app_custom_product_pages: typing.Optional[
            typing.List[
                typing_extensions.Literal[
                    "app",
                    "appCustomProductPageVersions",
                    "appStoreVersionTemplate",
                    "customProductPageTemplate",
                    "name",
                    "url",
                    "visible",
                ]
            ]
        ] = None,
        filter_state: typing.Optional[
            typing.List[
                typing_extensions.Literal[
                    "PREPARE_FOR_SUBMISSION",
                    "READY_FOR_REVIEW",
                    "WAITING_FOR_REVIEW",
                    "IN_REVIEW",
                    "ACCEPTED",
                    "APPROVED",
                    "REPLACED_WITH_NEW_VERSION",
                    "REJECTED",
                ]
            ]
        ] = None,
        include: typing.Optional[
            typing.List[
                typing_extensions.Literal[
                    "appCustomProductPage", "appCustomProductPageLocalizations"
                ]
            ]
        ] = None,
        limit: typing.Optional[int] = None,
        limit_app_custom_product_page_localizations: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.AppCustomProductPageVersionsResponse:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if fields_app_custom_product_page_localizations is not None:
            _query["fields[appCustomProductPageLocalizations]"] = encode_param(
                fields_app_custom_product_page_localizations, False
            )
        if fields_app_custom_product_page_versions is not None:
            _query["fields[appCustomProductPageVersions]"] = encode_param(
                fields_app_custom_product_page_versions, False
            )
        if fields_app_custom_product_pages is not None:
            _query["fields[appCustomProductPages]"] = encode_param(
                fields_app_custom_product_pages, False
            )
        if filter_state is not None:
            _query["filter[state]"] = encode_param(filter_state, False)
        if include is not None:
            _query["include"] = encode_param(include, False)
        if limit is not None:
            _query["limit"] = encode_param(limit, False)
        if limit_app_custom_product_page_localizations is not None:
            _query["limit[appCustomProductPageLocalizations]"] = encode_param(
                limit_app_custom_product_page_localizations, False
            )
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="GET",
            path=f"/v1/appCustomProductPages/{id}/appCustomProductPageVersions",
            auth_names=["itc-bearer-token"],
            query_params=_query,
            cast_to=models.AppCustomProductPageVersionsResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
