"""File Generated by Sideko (sideko.dev)"""

from apple_python.core import (
    QueryParams,
    RequestOptions,
    SyncBaseClient,
    AsyncBaseClient,
    encode_param,
    default_request_options,
)
import typing
import typing_extensions
from apple_python.types.v1.app_infos.age_rating_declaration import models


class AgeRatingDeclarationClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)

    # register sync api methods (keep comment for code generation)
    def list(
        self,
        *,
        id: str,
        fields_age_rating_declarations: typing.Optional[
            typing.List[
                typing_extensions.Literal[
                    "ageRatingOverride",
                    "alcoholTobaccoOrDrugUseOrReferences",
                    "contests",
                    "gambling",
                    "gamblingAndContests",
                    "gamblingSimulated",
                    "horrorOrFearThemes",
                    "kidsAgeBand",
                    "matureOrSuggestiveThemes",
                    "medicalOrTreatmentInformation",
                    "profanityOrCrudeHumor",
                    "seventeenPlus",
                    "sexualContentGraphicAndNudity",
                    "sexualContentOrNudity",
                    "unrestrictedWebAccess",
                    "violenceCartoonOrFantasy",
                    "violenceRealistic",
                    "violenceRealisticProlongedGraphicOrSadistic",
                ]
            ]
        ] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.AgeRatingDeclarationResponse:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if fields_age_rating_declarations is not None:
            _query["fields[ageRatingDeclarations]"] = encode_param(
                fields_age_rating_declarations, False
            )
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="GET",
            path=f"/v1/appInfos/{id}/ageRatingDeclaration",
            auth_names=["itc-bearer-token"],
            query_params=_query,
            cast_to=models.AgeRatingDeclarationResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncAgeRatingDeclarationClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)

    # register async api methods (keep comment for code generation)
    async def list(
        self,
        *,
        id: str,
        fields_age_rating_declarations: typing.Optional[
            typing.List[
                typing_extensions.Literal[
                    "ageRatingOverride",
                    "alcoholTobaccoOrDrugUseOrReferences",
                    "contests",
                    "gambling",
                    "gamblingAndContests",
                    "gamblingSimulated",
                    "horrorOrFearThemes",
                    "kidsAgeBand",
                    "matureOrSuggestiveThemes",
                    "medicalOrTreatmentInformation",
                    "profanityOrCrudeHumor",
                    "seventeenPlus",
                    "sexualContentGraphicAndNudity",
                    "sexualContentOrNudity",
                    "unrestrictedWebAccess",
                    "violenceCartoonOrFantasy",
                    "violenceRealistic",
                    "violenceRealisticProlongedGraphicOrSadistic",
                ]
            ]
        ] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.AgeRatingDeclarationResponse:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if fields_age_rating_declarations is not None:
            _query["fields[ageRatingDeclarations]"] = encode_param(
                fields_age_rating_declarations, False
            )
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="GET",
            path=f"/v1/appInfos/{id}/ageRatingDeclaration",
            auth_names=["itc-bearer-token"],
            query_params=_query,
            cast_to=models.AgeRatingDeclarationResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
