"""File Generated by Sideko (sideko.dev)"""

from .resource_client import (
    AsyncAppStoreVersionPhasedReleasesClient,
    AppStoreVersionPhasedReleasesClient,
)


__all__ = [
    "AsyncAppStoreVersionPhasedReleasesClient",
    "AppStoreVersionPhasedReleasesClient",
]
