"""File Generated by Sideko (sideko.dev)"""

from apple_python.core import (
    to_encodable,
    SyncBaseClient,
    AsyncBaseClient,
    default_request_options,
    encode_param,
    QueryParams,
    RequestOptions,
)
from apple_python.resources.v1.analytics_report_requests.reports import (
    AsyncReportsClient,
    ReportsClient,
)
import typing
import typing_extensions
from apple_python.types.v1.analytics_report_requests import models, params


class AnalyticsReportRequestsClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.reports = ReportsClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)
    def create(
        self,
        *,
        data: params.AnalyticsReportRequestCreateRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.AnalyticsReportRequestResponse:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data, dump_with=params._SerializerAnalyticsReportRequestCreateRequest
        )
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="POST",
            path="/v1/analyticsReportRequests",
            auth_names=["itc-bearer-token"],
            json=_json,
            cast_to=models.AnalyticsReportRequestResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)

    def get(
        self,
        *,
        id: str,
        fields_analytics_report_requests: typing.Optional[
            typing.List[
                typing_extensions.Literal[
                    "accessType", "app", "reports", "stoppedDueToInactivity"
                ]
            ]
        ] = None,
        fields_analytics_reports: typing.Optional[
            typing.List[typing_extensions.Literal["category", "instances", "name"]]
        ] = None,
        include: typing.Optional[
            typing.List[typing_extensions.Literal["reports"]]
        ] = None,
        limit_reports: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.AnalyticsReportRequestResponse:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if fields_analytics_report_requests is not None:
            _query["fields[analyticsReportRequests]"] = encode_param(
                fields_analytics_report_requests, False
            )
        if fields_analytics_reports is not None:
            _query["fields[analyticsReports]"] = encode_param(
                fields_analytics_reports, False
            )
        if include is not None:
            _query["include"] = encode_param(include, False)
        if limit_reports is not None:
            _query["limit[reports]"] = encode_param(limit_reports, False)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="GET",
            path=f"/v1/analyticsReportRequests/{id}",
            auth_names=["itc-bearer-token"],
            query_params=_query,
            cast_to=models.AnalyticsReportRequestResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)

    def delete(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="DELETE",
            path=f"/v1/analyticsReportRequests/{id}",
            auth_names=["itc-bearer-token"],
            cast_to=type(None),
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncAnalyticsReportRequestsClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.reports = AsyncReportsClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
    async def create(
        self,
        *,
        data: params.AnalyticsReportRequestCreateRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.AnalyticsReportRequestResponse:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data, dump_with=params._SerializerAnalyticsReportRequestCreateRequest
        )
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="POST",
            path="/v1/analyticsReportRequests",
            auth_names=["itc-bearer-token"],
            json=_json,
            cast_to=models.AnalyticsReportRequestResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)

    async def get(
        self,
        *,
        id: str,
        fields_analytics_report_requests: typing.Optional[
            typing.List[
                typing_extensions.Literal[
                    "accessType", "app", "reports", "stoppedDueToInactivity"
                ]
            ]
        ] = None,
        fields_analytics_reports: typing.Optional[
            typing.List[typing_extensions.Literal["category", "instances", "name"]]
        ] = None,
        include: typing.Optional[
            typing.List[typing_extensions.Literal["reports"]]
        ] = None,
        limit_reports: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.AnalyticsReportRequestResponse:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if fields_analytics_report_requests is not None:
            _query["fields[analyticsReportRequests]"] = encode_param(
                fields_analytics_report_requests, False
            )
        if fields_analytics_reports is not None:
            _query["fields[analyticsReports]"] = encode_param(
                fields_analytics_reports, False
            )
        if include is not None:
            _query["include"] = encode_param(include, False)
        if limit_reports is not None:
            _query["limit[reports]"] = encode_param(limit_reports, False)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="GET",
            path=f"/v1/analyticsReportRequests/{id}",
            auth_names=["itc-bearer-token"],
            query_params=_query,
            cast_to=models.AnalyticsReportRequestResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)

    async def delete(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="DELETE",
            path=f"/v1/analyticsReportRequests/{id}",
            auth_names=["itc-bearer-token"],
            cast_to=type(None),
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
