"""File Generated by Sideko (sideko.dev)"""

from apple_python.core import (
    QueryParams,
    encode_param,
    default_request_options,
    RequestOptions,
    SyncBaseClient,
    AsyncBaseClient,
)
import typing
import typing_extensions
from apple_python.types.v1.in_app_purchases import models


class InAppPurchasesClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)

    # register sync api methods (keep comment for code generation)
    def get(
        self,
        *,
        id: str,
        fields_in_app_purchases: typing.Optional[
            typing.List[
                typing_extensions.Literal[
                    "apps", "inAppPurchaseType", "productId", "referenceName", "state"
                ]
            ]
        ] = None,
        include: typing.Optional[typing.List[typing_extensions.Literal["apps"]]] = None,
        limit_apps: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.InAppPurchaseResponse:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if fields_in_app_purchases is not None:
            _query["fields[inAppPurchases]"] = encode_param(
                fields_in_app_purchases, False
            )
        if include is not None:
            _query["include"] = encode_param(include, False)
        if limit_apps is not None:
            _query["limit[apps]"] = encode_param(limit_apps, False)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="GET",
            path=f"/v1/inAppPurchases/{id}",
            auth_names=["itc-bearer-token"],
            query_params=_query,
            cast_to=models.InAppPurchaseResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncInAppPurchasesClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)

    # register async api methods (keep comment for code generation)
    async def get(
        self,
        *,
        id: str,
        fields_in_app_purchases: typing.Optional[
            typing.List[
                typing_extensions.Literal[
                    "apps", "inAppPurchaseType", "productId", "referenceName", "state"
                ]
            ]
        ] = None,
        include: typing.Optional[typing.List[typing_extensions.Literal["apps"]]] = None,
        limit_apps: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.InAppPurchaseResponse:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if fields_in_app_purchases is not None:
            _query["fields[inAppPurchases]"] = encode_param(
                fields_in_app_purchases, False
            )
        if include is not None:
            _query["include"] = encode_param(include, False)
        if limit_apps is not None:
            _query["limit[apps]"] = encode_param(limit_apps, False)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="GET",
            path=f"/v1/inAppPurchases/{id}",
            auth_names=["itc-bearer-token"],
            query_params=_query,
            cast_to=models.InAppPurchaseResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
