"""File Generated by Sideko (sideko.dev)"""

from .resource_client import (
    AsyncGameCenterLeaderboardSetReleasesClient,
    GameCenterLeaderboardSetReleasesClient,
)


__all__ = [
    "AsyncGameCenterLeaderboardSetReleasesClient",
    "GameCenterLeaderboardSetReleasesClient",
]
