"""File Generated by Sideko (sideko.dev)"""

from apple_python.core import (
    encode_param,
    SyncBaseClient,
    RequestOptions,
    default_request_options,
    AsyncBaseClient,
    QueryParams,
)
import typing
import typing_extensions
from apple_python.types.v1.scm_git_references import models


class ScmGitReferencesClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)

    # register sync api methods (keep comment for code generation)
    def get(
        self,
        *,
        id: str,
        fields_scm_git_references: typing.Optional[
            typing.List[
                typing_extensions.Literal[
                    "canonicalName", "isDeleted", "kind", "name", "repository"
                ]
            ]
        ] = None,
        include: typing.Optional[
            typing.List[typing_extensions.Literal["repository"]]
        ] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.ScmGitReferenceResponse:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if fields_scm_git_references is not None:
            _query["fields[scmGitReferences]"] = encode_param(
                fields_scm_git_references, False
            )
        if include is not None:
            _query["include"] = encode_param(include, False)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="GET",
            path=f"/v1/scmGitReferences/{id}",
            auth_names=["itc-bearer-token"],
            query_params=_query,
            cast_to=models.ScmGitReferenceResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncScmGitReferencesClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)

    # register async api methods (keep comment for code generation)
    async def get(
        self,
        *,
        id: str,
        fields_scm_git_references: typing.Optional[
            typing.List[
                typing_extensions.Literal[
                    "canonicalName", "isDeleted", "kind", "name", "repository"
                ]
            ]
        ] = None,
        include: typing.Optional[
            typing.List[typing_extensions.Literal["repository"]]
        ] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.ScmGitReferenceResponse:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if fields_scm_git_references is not None:
            _query["fields[scmGitReferences]"] = encode_param(
                fields_scm_git_references, False
            )
        if include is not None:
            _query["include"] = encode_param(include, False)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="GET",
            path=f"/v1/scmGitReferences/{id}",
            auth_names=["itc-bearer-token"],
            query_params=_query,
            cast_to=models.ScmGitReferenceResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
