"""File Generated by Sideko (sideko.dev)"""

from __future__ import annotations
import io
import typing
import pydantic
import typing_extensions

HttpxFile = typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]


class AppPromotedPurchasesLinkagesRequestDataItem(typing_extensions.TypedDict):
    """
    No description specified
    """

    id: typing_extensions.Required[str]
    type: typing_extensions.Required[typing_extensions.Literal["promotedPurchases"]]


class _SerializerAppPromotedPurchasesLinkagesRequestDataItem(pydantic.BaseModel):
    """
    Serializer for AppPromotedPurchasesLinkagesRequestDataItem handling case conversions
    and file omitions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    id: str = pydantic.Field(alias="id")
    type: typing_extensions.Literal["promotedPurchases"] = pydantic.Field(alias="type")


class AppPromotedPurchasesLinkagesRequest(typing_extensions.TypedDict):
    """
    No description specified
    """

    data: typing_extensions.Required[
        typing.List[AppPromotedPurchasesLinkagesRequestDataItem]
    ]


class _SerializerAppPromotedPurchasesLinkagesRequest(pydantic.BaseModel):
    """
    Serializer for AppPromotedPurchasesLinkagesRequest handling case conversions
    and file omitions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    data: typing.List[_SerializerAppPromotedPurchasesLinkagesRequestDataItem] = (
        pydantic.Field(alias="data")
    )
