"""File Generated by Sideko (sideko.dev)"""

from apple_python.core import (
    SyncBaseClient,
    RequestOptions,
    default_request_options,
    to_encodable,
    AsyncBaseClient,
    QueryParams,
    encode_param,
)
from apple_python.resources.v1.alternative_distribution_packages.versions import (
    VersionsClient,
    AsyncVersionsClient,
)
import typing
import typing_extensions
from apple_python.types.v1.alternative_distribution_packages import models, params


class AlternativeDistributionPackagesClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.versions = VersionsClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)
    def create(
        self,
        *,
        data: params.AlternativeDistributionPackageCreateRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.AlternativeDistributionPackageResponse:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data,
            dump_with=params._SerializerAlternativeDistributionPackageCreateRequest,
        )
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="POST",
            path="/v1/alternativeDistributionPackages",
            auth_names=["itc-bearer-token"],
            json=_json,
            cast_to=models.AlternativeDistributionPackageResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)

    def get(
        self,
        *,
        id: str,
        fields_alternative_distribution_package_versions: typing.Optional[
            typing.List[
                typing_extensions.Literal[
                    "alternativeDistributionPackage",
                    "deltas",
                    "fileChecksum",
                    "state",
                    "url",
                    "urlExpirationDate",
                    "variants",
                    "version",
                ]
            ]
        ] = None,
        fields_alternative_distribution_packages: typing.Optional[
            typing.List[typing_extensions.Literal["appStoreVersion", "versions"]]
        ] = None,
        include: typing.Optional[
            typing.List[typing_extensions.Literal["versions"]]
        ] = None,
        limit_versions: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.AlternativeDistributionPackageResponse:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if fields_alternative_distribution_package_versions is not None:
            _query["fields[alternativeDistributionPackageVersions]"] = encode_param(
                fields_alternative_distribution_package_versions, False
            )
        if fields_alternative_distribution_packages is not None:
            _query["fields[alternativeDistributionPackages]"] = encode_param(
                fields_alternative_distribution_packages, False
            )
        if include is not None:
            _query["include"] = encode_param(include, False)
        if limit_versions is not None:
            _query["limit[versions]"] = encode_param(limit_versions, False)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="GET",
            path=f"/v1/alternativeDistributionPackages/{id}",
            auth_names=["itc-bearer-token"],
            query_params=_query,
            cast_to=models.AlternativeDistributionPackageResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncAlternativeDistributionPackagesClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.versions = AsyncVersionsClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
    async def create(
        self,
        *,
        data: params.AlternativeDistributionPackageCreateRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.AlternativeDistributionPackageResponse:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data,
            dump_with=params._SerializerAlternativeDistributionPackageCreateRequest,
        )
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="POST",
            path="/v1/alternativeDistributionPackages",
            auth_names=["itc-bearer-token"],
            json=_json,
            cast_to=models.AlternativeDistributionPackageResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)

    async def get(
        self,
        *,
        id: str,
        fields_alternative_distribution_package_versions: typing.Optional[
            typing.List[
                typing_extensions.Literal[
                    "alternativeDistributionPackage",
                    "deltas",
                    "fileChecksum",
                    "state",
                    "url",
                    "urlExpirationDate",
                    "variants",
                    "version",
                ]
            ]
        ] = None,
        fields_alternative_distribution_packages: typing.Optional[
            typing.List[typing_extensions.Literal["appStoreVersion", "versions"]]
        ] = None,
        include: typing.Optional[
            typing.List[typing_extensions.Literal["versions"]]
        ] = None,
        limit_versions: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.AlternativeDistributionPackageResponse:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if fields_alternative_distribution_package_versions is not None:
            _query["fields[alternativeDistributionPackageVersions]"] = encode_param(
                fields_alternative_distribution_package_versions, False
            )
        if fields_alternative_distribution_packages is not None:
            _query["fields[alternativeDistributionPackages]"] = encode_param(
                fields_alternative_distribution_packages, False
            )
        if include is not None:
            _query["include"] = encode_param(include, False)
        if limit_versions is not None:
            _query["limit[versions]"] = encode_param(limit_versions, False)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="GET",
            path=f"/v1/alternativeDistributionPackages/{id}",
            auth_names=["itc-bearer-token"],
            query_params=_query,
            cast_to=models.AlternativeDistributionPackageResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
