"""File Generated by Sideko (sideko.dev)"""

from apple_python.core import (
    to_encodable,
    AsyncBaseClient,
    RequestOptions,
    default_request_options,
    SyncBaseClient,
)
from apple_python.types.v2.sandbox_testers_clear_purchase_history_request import (
    params,
    models,
)
import typing


class SandboxTestersClearPurchaseHistoryRequestClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)

    # register sync api methods (keep comment for code generation)
    def create(
        self,
        *,
        data: params.SandboxTestersClearPurchaseHistoryRequestV2CreateRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.SandboxTestersClearPurchaseHistoryRequestV2Response:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data,
            dump_with=params._SerializerSandboxTestersClearPurchaseHistoryRequestV2CreateRequest,
        )
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="POST",
            path="/v2/sandboxTestersClearPurchaseHistoryRequest",
            auth_names=["itc-bearer-token"],
            json=_json,
            cast_to=models.SandboxTestersClearPurchaseHistoryRequestV2Response,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncSandboxTestersClearPurchaseHistoryRequestClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)

    # register async api methods (keep comment for code generation)
    async def create(
        self,
        *,
        data: params.SandboxTestersClearPurchaseHistoryRequestV2CreateRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.SandboxTestersClearPurchaseHistoryRequestV2Response:
        """
        no description available
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data,
            dump_with=params._SerializerSandboxTestersClearPurchaseHistoryRequestV2CreateRequest,
        )
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="POST",
            path="/v2/sandboxTestersClearPurchaseHistoryRequest",
            auth_names=["itc-bearer-token"],
            json=_json,
            cast_to=models.SandboxTestersClearPurchaseHistoryRequestV2Response,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
